// <auto-generated />
using System;
using BackendAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackendAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251105004323_Mise à jour AnneScolaireId")]
    partial class MiseàjourAnneScolaireId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackendAPI.Models.Annee_Scolaire", b =>
                {
                    b.Property<int>("AnneeScolaire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AnneScolaireId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("AnneeScolaire");

                    b.ToTable("Annee_Scolaires");
                });

            modelBuilder.Entity("BackendAPI.Models.Ecole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdEcole")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdresseEcole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Arrete_Agreement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HistoriqueEcole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("LatitudeEcole")
                        .HasColumnType("float");

                    b.Property<double>("LongitudeEcole")
                        .HasColumnType("float");

                    b.Property<string>("Matricule_Secope")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoEcole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitreEcole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Ecoles");
                });

            modelBuilder.Entity("BackendAPI.Models.Eleve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdEleve")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateNaisEleve")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LieuNaisEleve")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomEleve")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoEleve")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostNomEleve")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SexeEleve")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Eleves");
                });

            modelBuilder.Entity("BackendAPI.Models.Inscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdInscription")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnneScolaireId")
                        .HasColumnType("int");

                    b.Property<int?>("AnneeScolaire1")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2");

                    b.Property<int>("EcoleId")
                        .HasColumnType("int");

                    b.Property<int>("EleveId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnneeScolaire1");

                    b.HasIndex("EcoleId");

                    b.HasIndex("EleveId");

                    b.ToTable("Inscriptions");
                });

            modelBuilder.Entity("BackendAPI.Models.Inscription", b =>
                {
                    b.HasOne("BackendAPI.Models.Annee_Scolaire", "AnneeScolaire")
                        .WithMany("Inscriptions")
                        .HasForeignKey("AnneeScolaire1");

                    b.HasOne("BackendAPI.Models.Ecole", "Ecole")
                        .WithMany("Inscriptions")
                        .HasForeignKey("EcoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPI.Models.Eleve", "Eleve")
                        .WithMany("Inscriptions")
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnneeScolaire");

                    b.Navigation("Ecole");

                    b.Navigation("Eleve");
                });

            modelBuilder.Entity("BackendAPI.Models.Annee_Scolaire", b =>
                {
                    b.Navigation("Inscriptions");
                });

            modelBuilder.Entity("BackendAPI.Models.Ecole", b =>
                {
                    b.Navigation("Inscriptions");
                });

            modelBuilder.Entity("BackendAPI.Models.Eleve", b =>
                {
                    b.Navigation("Inscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
